name: Haskell CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: sudo apt-get install liblbfgsb-dev

    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: '9.4.5'
        cabal-version: '3.8.1.0'
        enable-stack: true

    - name: Setup stack
      run: stack config set system-ghc --global true

    - name: Cache ~/.stack
      uses: actions/cache@v3
      env:
        cache-name: cache-stack
      with:
        path: ${{ steps.setup-haskell.outputs.stack-root }}
        key: ${{ runner.os }}-stack

    - name: Install dependencies
      run: stack build --test --no-run-tests --bench --no-run-benchmarks --only-dependencies

    - name: Build
      run: stack build --test --no-run-tests --bench --no-run-benchmarks

    - name: Run tests
      run: stack test
